### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by adamchainz** [ingresso-group/pyticketswitch#15]
Hi guys,

Just been upgrading our pip packages, and upgrading pyticketswitch is a bit confusing. The changelog is missing versions 1.8.8 to 1.8.10, which I had to look in github for, but which commits like https://github.com/ingresso-group/pyticketswitch/commit/560bd6c2b8af3081794046ad1593842f7c837049 muddy the water around. 

And then there was just a minor release 1.9.0 for which the changelog reads like you just updated the tests, but which makes me feel like I'm missing something about how I should use `pyticketswitch` in tests?

I think just a little more explanation in the changelog would be helpful, especially for the missing versions. Thanks.

**Comment by rossgray** [comment]
Hi @adamchainz, 

Sorry for the confusion. There was a bit of a versioning problem between 1.8.8 and 1.8.9 (I think the wrong commits were tagged with the version).

I agree we should have more detail in the changelog, so we will try to address that. 

For the latest release (1.9.0) I just added a package to mock our calls to the Ticketswitch API, so that we don't have an external dependency in our tests that could fail. Therefore, you shouldn't need to do anything different when running tests (although if you add a new test there may be a .yaml file that contains the recorded API response that you need to commit)

Thanks, and sorry again!

**Comment by adamchainz** [comment]
Ok thanks!
